// src/lib/certificates.ts
// Generates and stores verifiable PDF certificates
// Stack: PDFKit + qrcode + S3/R2

import { prisma } from "@/lib/prisma";
import { CertificateLevel } from "@prisma/client";

const LEVEL_NAMES: Record<CertificateLevel, string> = {
  EXPLORER:     "AI Explorer",
  CREATOR:      "AI Creator",
  BUILDER:      "AI Builder",
  ENTREPRENEUR: "AI Entrepreneur",
  MASTER:       "VYZIO Master",
};

const LEVEL_REQUIREMENTS: Record<CertificateLevel, { lessons: number; projects: number }> = {
  EXPLORER:     { lessons: 150, projects: 1 },
  CREATOR:      { lessons: 175, projects: 1 },
  BUILDER:      { lessons: 200, projects: 2 },
  ENTREPRENEUR: { lessons: 100, projects: 2 },
  MASTER:       { lessons: 625, projects: 6 },
};

// ─── Check if user qualifies for a certificate ───────────────
export async function checkCertificateEligibility(
  userId: string,
  level: CertificateLevel
): Promise<{ eligible: boolean; reason?: string }> {
  const req = LEVEL_REQUIREMENTS[level];

  // Map cert level → numeric level
  const levelMap: Record<CertificateLevel, number[]> = {
    EXPLORER:     [1],
    CREATOR:      [2],
    BUILDER:      [3],
    ENTREPRENEUR: [4],
    MASTER:       [1, 2, 3, 4],
  };

  const completedLessons = await prisma.lessonProgress.count({
    where: {
      userId,
      completed: true,
      lesson: { world: { level: { number: { in: levelMap[level] } } } },
    },
  });

  if (completedLessons < req.lessons) {
    return {
      eligible: false,
      reason: `Necesitas ${req.lessons} lecciones completadas. Llevas ${completedLessons}.`,
    };
  }

  const completedProjects = await prisma.portfolioItem.count({
    where: {
      userId,
      lessonId: { not: null },
    },
  });

  if (completedProjects < req.projects) {
    return {
      eligible: false,
      reason: `Necesitas ${req.projects} proyecto(s) completado(s). Llevas ${completedProjects}.`,
    };
  }

  // Check not already issued
  const existing = await prisma.certificate.findFirst({
    where: { userId, level },
  });
  if (existing) {
    return { eligible: false, reason: "Ya tienes este certificado." };
  }

  return { eligible: true };
}

// ─── Issue certificate ───────────────────────────────────────
export async function issueCertificate(
  userId: string,
  level: CertificateLevel
): Promise<{ certificateId: string; verifyUrl: string; uuid: string }> {
  const { eligible, reason } = await checkCertificateEligibility(userId, level);
  if (!eligible) throw new Error(reason);

  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw new Error("User not found");

  const [lessonCount, projectCount, gamification] = await Promise.all([
    prisma.lessonProgress.count({ where: { userId, completed: true } }),
    prisma.portfolioItem.count({ where: { userId } }),
    prisma.gamification.findUnique({ where: { userId } }),
  ]);

  // Create DB record (uuid auto-generated by Prisma cuid)
  const cert = await prisma.certificate.create({
    data: {
      userId,
      level,
      levelId: await getLevelId(level),
      lessonsCompleted: lessonCount,
      projectsCompleted: projectCount,
      totalXpAtIssuance: gamification?.xpTotal ?? 0,
      verifyUrl: "", // filled after we know the cert ID
    },
  });

  const verifyUrl = `${process.env.NEXT_PUBLIC_APP_URL}/verify/${cert.uuid}`;

  // Update with verifyUrl
  await prisma.certificate.update({
    where: { id: cert.id },
    data: { verifyUrl },
  });

  // Queue PDF generation (background job via BullMQ)
  // In production: await certQueue.add('generate-cert', { certId: cert.id });

  return { certificateId: cert.id, verifyUrl, uuid: cert.uuid };
}

// ─── Public verification ─────────────────────────────────────
export async function verifyCertificate(uuid: string) {
  const cert = await prisma.certificate.findUnique({
    where: { uuid },
    include: {
      user: {
        select: { displayName: true, username: true, avatarEmoji: true },
      },
      courseLevel: true,
    },
  });

  if (!cert) return null;

  return {
    isValid: true,
    certificateId: cert.uuid,
    level: cert.level,
    levelName: LEVEL_NAMES[cert.level],
    issuedTo: cert.user.displayName,
    issuedAt: cert.issuedAt,
    lessonsCompleted: cert.lessonsCompleted,
    projectsCompleted: cert.projectsCompleted,
    profileUrl: `${process.env.NEXT_PUBLIC_APP_URL}/@${cert.user.username}`,
  };
}

async function getLevelId(certLevel: CertificateLevel): Promise<string> {
  const levelMap: Record<CertificateLevel, number> = {
    EXPLORER: 1, CREATOR: 2, BUILDER: 3, ENTREPRENEUR: 4, MASTER: 1,
  };
  const level = await prisma.level.findFirst({
    where: { number: levelMap[certLevel] },
  });
  return level?.id ?? "";
}
